openapi: 3.0.1
info:
  title: API de Categorias
  description: "API de listagem de categorias"
  version: 1.0.0
  contact:
    name: Suporte a Devs
    email: gfcarvalho@gmail.com
    url: https://github.com/gfcarvalhos
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Link desenvolvedor
  url: https://github.com/gfcarvalhos
tags: 
- name: Categories - Essentials
  description: Ações de taks essentials
- name: Categories - Admin
  description: Ações de tasks desejáveis
servers:
  - url: http://localhost:3000/
paths:
  /categories:
    get:
      tags:
      - Categories - Essentials
      summary: Lista das categorias
      description: "Retorna a lista completa de categorias"
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
        '404':
          description: Não há categorias cadastradas
          content:
            application/json:
              example: "Not Found"
  /admin/categories:
    post:
      tags:
      - Categories - Essentials
      summary: Insere nova categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
        required: true
      security: 
      - auth: []
      responses:
        '201':
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
  /categories/{id}:
    get:
      tags:
      - Categories - Essentials
      summary: Retorna categoria com id especificado
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
        '404':
          description: Não há categorias cadastradas
          content:
            application/json:
              example: "Not Found"
  /admin/categories/{id}:
    put:
      tags:
      - Categories - Admin
      summary: Alteração dos dados de uma categoria
      parameters: 
      - name: id
        in: path
        description: ID da categoria a ser atualizada
        schema:
          type: string
        required: true
      requestBody:
        description: Atualiza os dados de categoria já existentes
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        '200':
          description: Categoria atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        '404':
          description: Erro de atualização
          content:
            application/json:
              example: "Erro durante atualização"
    delete:
      tags:
      - Categories - Admin
      summary: Deleta categoria
      parameters: 
      - name: id
        in: path
        description: ID da categoria a ser deletada
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Categoria deletada
          content:
            application/json:
              example: "Categoria deletada"
        '404':
          description: Erro de execução
          content:
            application/json:
              example: "Erro durante a execução"
  /admin/categories/active/{id}:
    put:
      tags:
      - Categories - Admin
      summary: Alteração dos dados de uma categoria
      parameters: 
      - name: id
        in: path
        description: ID da categoria a ser atualizada
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Categoria ativada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        '404':
          description: Erro na atualização
          content:
            application/json:
              example: "Erro durante atualização"
  
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      